---
- name: Deploy Movie Recommendation Stack to Kubernetes
  hosts: all
  become: yes
  vars_files:
   - vault.yml
  vars:
    k8s_dir: "{{ playbook_dir }}/../k8s"
    kubeconfig_path: "/root/.kube/config"
    manifest_order:
      # - mongodb-secret.yaml
      - ml-pvcs.yaml
      - ml-service.yaml
      - backend-service.yaml
      - frontend-service.yaml
      - ml-deployment.yaml
      - backend-deployment.yaml
      - frontend-deployment.yaml
      - ml-hpa.yaml
      - backend-hpa.yaml
      - frontend-hpa.yaml
      - logstash.yaml
      - elasticsearch.yaml
      - kibana.yaml

  roles:
    - k8s
